name: build-and-deploy-jupyterlite
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install jupyterlite-core jupyterlite-pyodide-kernel jupyter-server ipywidgets anywidget
      # add other federated kernels as needed
      - run: jupyter lite build --contents demo --output-dir dist
      - run: |
            # Install the vectorizedplot Mathics3-Module from the github repo
            git clone --depth 1 https://github.com/Mathics3/Mathics3-Module-vectorizedplot.git
            cd Mathics3-Module-vectorizedplot
            python -m pip install --no-build-isolation -e .
            cd ..      
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }
  deploy:
    needs: build
    permissions: { pages: write, id-token: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
